version: 2.1

jobs:
  porter-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Setup porter"
          command: |
            /bin/bash -c "$(curl -fsSL https://install.porter.run)"
      - run:
          name: Set Porter Environment Variables
          command: |
            echo "export PORTER_PR_NUMBER=${CIRCLE_PULL_REQUEST##*/}" >> $BASH_ENV
            echo "export PORTER_TAG=$(git rev-parse --short HEAD)" >> $BASH_ENV
            echo "export PORTER_TOKEN=$PORTER_STACK_1_1" >> $BASH_ENV
      - run:
          name: "Deploy stack"
          command: |
            porter apply -f ./porter.yaml
          environment:
            PORTER_CLUSTER: "1"
            PORTER_HOST: https://newt-worthy-gazelle.ngrok-free.app
            PORTER_PROJECT: "1"
            PORTER_STACK_NAME: circleci

workflows:
  porter-deploy-workflow:
    jobs:
      - porter-deploy
