version: 2.1

jobs:
  porter-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Github tag
          command: |
            echo "export sha_short=$(git rev-parse --short HEAD)" >> $BASH_ENV
      - run:
          name: "Setup porter"
          command: |
            /bin/bash -c "$(curl -fsSL https://install.porter.run)"
      - run:
          name: "Deploy stack"
          command: |
            env
            porter apply -f ./porter.yaml
          environment:
            PORTER_CLUSTER: "1"
            PORTER_HOST: https://newt-worthy-gazelle.ngrok-free.app
            PORTER_PR_NUMBER: "$CIRCLE_PR_NUMBER"
            PORTER_PROJECT: "1"
            PORTER_STACK_NAME: circleci
            PORTER_TAG: "$sha_short"
            PORTER_TOKEN: "$PORTER_TOKEN_1_1"

workflows:
  porter-deploy-workflow:
    jobs:
      - porter-deploy
